### PR TITLE
add scrum2b, a plugin for redmine

### PR DESCRIPTION
**Pull request by xluffy**
Hmm, i forget to pull from upstream before commit & push. So I commited a mesg for resolving conflict. So sorry

### CODE REVIEW

**Comment by lewtds** [comment]
Just rebase your branch against `origin/master` to remove the redundant commit then `push --force`, the PR will be updated. ; )

**Comment by lewtds** [comment]
Also, I think the description is a bit vague. How about "Scrum extension for Redmine"?

**Comment by xluffy** [comment]
Git rebase is awesome, i fixed it, plz review @lewtds

**Comment by lewtds** [comment]
Thanks.

**Pull request merged**
