### PR TITLE
Add capstone-engine, a ultimate Disassembly Framework

### PR DESCRIPTION
**Pull request by xluffy**

### CODE REVIEW

**Comment by lewtds** [comment]
Nice. But I think this should belong to **Developer tool** and the project name should be just **capstone**. Would you mind updating the pull request?

**Comment by xluffy** [comment]
ok, i'll update it.

btw, project name sort alphabet ?

**Comment by lewtds** [comment]
Yeah. To update, just push more commits into the branch of the request.

**Comment by lewtds** [comment]
Merged. Thanks!

**Pull request merged**
